from .db_import import db


class Transactions(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    deposit_id = db.Column(db.String(120), unique=True, index=True)
    idempotency_key = db.Column(db.String(255), unique=True, index=True)
    tx_id = db.Column(db.String(120))
    status = db.Column(db.String(20))
    ttype = db.Column(db.String(10))
    score = db.Column(db.Numeric(precision=7, scale=5), nullable=True)
    crypto = db.Column(db.String(20))
    amount = db.Column(db.Numeric(precision=52, scale=26), default=0) 
    address = db.Column(db.String(128))
    uid = db.Column(db.String(128))
    data = db.Column(db.Text)
    provider = db.Column(db.String(30), default="koinkyt")
    provider_status = db.Column(db.String(30))
    asset = db.Column(db.String(30))
    network = db.Column(db.String(30))
    threshold = db.Column(db.Numeric(precision=7, scale=5), nullable=True)
    signals_json = db.Column(db.Text)
    raw_response_json = db.Column(db.Text)
    report_url = db.Column(db.String(512))
    error_code = db.Column(db.String(80))
    error_message = db.Column(db.Text)
    next_retry_at = db.Column(db.DateTime)
    timeout_at = db.Column(db.DateTime)
    attempts = db.Column(db.Numeric(precision=7, scale=2), default=0)
    created_at = db.Column(db.DateTime, default=db.func.current_timestamp())
    last_update = db.Column(db.DateTime, default=db.func.current_timestamp(),
                                        onupdate=db.func.current_timestamp()) 
    __table_args__ = (db.UniqueConstraint('id'), )
